angular.module('OrderCloud-HeaderNavigation', []);
angular.module('OrderCloud-HeaderNavigation')
    .directive('headernavigation', headernavigation)
;

function headernavigation() {
    return {
        restrict: 'E',
        template: template,
        controller: 'NavCtrl'
    };

    function template() {
        return [
            '<style>',
            '.alert-banner {text-align: center;background-color: #FF7F30;color: white;font-size: 20px;font-weight: 300;margin-bottom: 0;}',
            '.navUL {display:flex;}',
            '.navItems {padding: .5rem 1rem;margin-top: 23px;text-transform: capitalize;;letter-spacing: -1px;color: #313131;}',
            '.nav-link {font-size: 1.4rem;color: black;letter-spacing: 0.06rem;}',
			'nav-link:hover {color:white;}',
            '.headerRow {display: flex;}',
            '.header-decoration {height: 40px;background-color: #B52229;}',
            '.user-search {display:flex;}',
            '.user-icon {padding-top:18px;}',
            '.fa-user {color:black;font-size: 23px;}',
            '.fa-user:hover {font-size: 24px !important;}',
            '.fa-search {font-size:18px;}',
            '.fa-search:hover {font-size:19px;}',
            '.main-nav-spendingaccount {font-size: 15px;font-weight: 600;letter-spacing: 0;color: rgb(0, 38, 62);float: right;margin-right: 6%;position: relative;top: 15px;}',
            '</style>',
            /*'<div>',
              '<div class="alert alert-warning alert-dismissable alert-banner">',
                '<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>',
                'Checkout our Exclusive Astreea Dispensers and Astreea Safe Sanitizers <a href="catalog/usdp_ast" style="color: white;font-weight: 500;">Here</a>',
              '</div>',h
            '</div>',*/
            
            /*'<div class="header-decoration">',
						  '<ul class="top-nav">',
							'<li class="top-nav-items">',
							'<a class="top-nav-link" href="admin">',
							'{{\'User Information\' | r | xlat}}',
							'</a>',
							'</li>',
							'<li class="top-nav-items">',
							'<a class="top-nav-link" href="addresses">',
							'{{\'Address Book\' | r | xlat}}',
							'</a>',
							'</li>',
							'<li class="top-nav-items">',
							'<a class="top-nav-link" href="contactus">',
							'{{\'Contact Us\' | r | xlat}}',
							'</a>',
							'</li>',
	
							'</ul>',
            '</div>',*/
                /*SPENDING ACCOUNTS NAV*/
                '<ul>',
                '<li ng-if="userSpendingAccounts" class="spendingaccounts main-nav-spendingaccount">',
                    '<span class="hidden-xs hidden-sm">Spending Account: {{userSpendingAccounts[0].Balance | currency}}</span>',
                '</li>',
                /*END SPENDING ACCOUNTS NAV*/
                '</ul>',

            '<section class="header-navigation" style="height:100px;">',
            '<div class="row headerRow" style="height: 75px;padding-top:10px;">',

                '<div class="col-xs-12 col-sm-12 col-md-3 col-lg-2 pull-left navImages main-logo" style="">',
                '<a ng-show="Four51User.isAuthenticated()" href="catalog">',
                /*'<img class="headerLogo" src="{{user.Company.LogoUrl}}" width="200px" height=""/>',*/
                '<img class="headerLogo" src="https://images.hertz.com/misc/overlay/hertz-logo-black.png" width="150px" height=""/>',
                '</a>',
                '</div>',

                '<div class="col-xs-12 col-sm-12 col-md-7 col-lg-6 hidden-xs hidden-sm" style="">',
                '<ul class="navUL">',

                '<li class="products navItems" ng-class="{\'active\': isActive([\'catalog\'])}">',
                '<a class="nav-link" href="catalog">',
                '{{\'Home\' | r | xlat}}',
                '</a>',
                '</li>',
                
                '<li class="order navItems" ng-class="{\'active\': isActive([\'order\'])}">',
                '<a class="nav-link" href="order">',
                '{{\'Orders\' | r | xlat}}',
                '<span ng-if="waitingOrderCount > 0" class="badge" style="margin-left: 5px;">{{waitingOrderCount}}</span>',
                '</a>',
                '</li>',
                
                '<li class="report navItems"  ng-show="hertzChampionUser || dollarChampionUser || thriftyChampionUser">',
                '<a class="nav-link" href="https://thumbprint.com/hertz/UniformReturn" target="_blank">',
                '{{\'Uniform Returns\' | r | xlat}}',
                '</a>',
                '</li>',
                
                '<li class="order navItems" ng-class="{\'active\': isActive([\'faq\'])}" ng-show="hertzChampionUser || dollarChampionUser || thriftyChampionUser">',
                '<a class="nav-link" href="faq">',
                '{{\'FAQ\' | r | xlat}}',
                '</a>',
                '</li>',
                
                '<li class="order navItems" ng-class="{\'active\': isActive([\'allofaq\'])}" ng-show="hertzUser || dollarUser || thriftyUser">',
                '<a class="nav-link" href="allofaq">',
                '{{\'FAQ\' | r | xlat}}',
                '</a>',
                '</li>',
                
                //  '<li class="report navItems" ng-show="user.Type ==\'Customer\' && user.Permissions.contains(\'AdvancedReporting\')" ng-class="{\'active\': isActive([\'reports\'])}">',
              //  '<a class="nav-link" href="reports">',
              //  '{{\'Reports\' | r | xlat}}',
              //  '</a>',
              //  '</li>',
    


								/*'<li class="products navItems" ng-class="{\'active\': isActive([\'mill_apparel\'])}">',
								'<a class="nav-link" href="catalog/mill_apparel">',
								'{{\'Apparel\' | r | xlat}}',
								'</a>',
								'</li>',*/

								/*'<li class="products navItems" ng-class="{\'active\': isActive([\'mill_stationary\'])}">',
								'<a class="nav-link" href="catalog/mill_stationary">',
								'{{\'Stationary\' | r | xlat}}',
								'</a>',
								'</li>',*/

              //  '<li class="report navItems" ng-show="user.Type ==\'Customer\' && user.Permissions.contains(\'AdvancedReporting\')" ng-class="{\'active\': isActive([\'reports\'])}">',
              //  '<a class="nav-link" href="reports">',
              //  '{{\'Reports\' | r | xlat}}',
              //  '</a>',
              //  '</li>',

                /*'<li class="order navItems" ng-show="user.Permissions.contains(\'ViewContactUs\')" ng-class="{\'active\': isActive([\'contactus\'])}">',
                '<a href="contactus">',
                '{{\'Contact Us\' | r | xlat}}',
                '</a>',
                '</li>',*/

                /*'<li class="report navItems" ng-show="adminMember === true">',
                '<a class="nav-link" href="https://insights.thumbprint.com/open-view/2093611000043311742" target="_blank">',
                '{{\'Insights\' | r | xlat}}',
                '</a>',
                '</li>',*/
      

            /*'<li class="dropdown visible-md visible-lg navItems" ng-class="{\'active\': isActive([\'tts_bags\'])}">',
            '<a class="nav-link" class="dropdown-toggle" data-toggle="dropdown">',
            '<span class="hidden-xs">{{\'Accessories\' | r | xlat}}</span>',
            '<b class="caret"></b>',
            '</a>',
            '<ul class="dropdown-menu">',
            '<li class="apparel">',
            '<a href="catalog/tts_bags">',
            '{{\'Bags\' | r | xlat}}',
            '</a>',
            '</li>',
            '</ul>',
            '</li>',*/
                /*'<li class="products navItems" ng-class="{\'active\': isActive([\'tt_con_all\'])}" ng-show="conSpringUser || conOfficeSpringUser">',
                '<a class="nav-link" href="catalog/tt_con_all">',
                '{{\'Spring 2025 Construction\' | r | xlat}}',
                '</a>',
                '</li>',*/


                '<li class="products navItems" ng-class="{\'active\': isActive([\'tth_allpromo\'])}" ng-show="adminUser || purchaserUser">',
                '<a class="nav-link" href="catalog/tth_allpromo">',
                '{{\'Promo\' | r | xlat}}',
                '</a>',
                '</li>',
                '<li class="products navItems" ng-class="{\'active\': isActive([\'tts_marketing\'])}" ng-show="adminUser || user.Username === \'ThomsponThrift_ncrosby@thompsonthrift.com\' || user.Username === \'ThomsponThrift_kwhitaker@thompsonthrift.com\' || user.Username === \'ThomsponThrift_mhettinger@thompsonthrift.com\'">',
                    '<a class="nav-link" href="catalog/tts_marketing">',
                        '{{\'Marketing\' | r | xlat}}',
                    '</a>',
                '</li>',
                '<li class="products navItems" ng-class="{\'active\': isActive([\'tts_marketing\'])}" ng-show="hertzChampionUser || dollarChampionUser || thriftyChampionUser">',
                    '<a class="nav-link" href="uniforminsights">',
                        '{{\'UC Insights\' | r | xlat}}',
                    '</a>',
                '</li>',
                '<li class="products navItems" ng-class="{\'active\': isActive([\'tts_marketing\'])}" ng-show="insightsUser">',
                    '<a class="nav-link" href="insights">',
                        '{{\'Insights\' | r | xlat}}',
                    '</a>',
                '</li>',

                '<li class="dropdown visible-md visible-lg navItems" ng-class="{\'active\': isActive([\'admin\', \'addresses\', \'address\', \'messages\', \'message\', \'favoriteorders\'])}">',
                '<a class="nav-link" class="dropdown-toggle" data-toggle="dropdown">',
                '<span class="hidden-xs">{{\'Account\' | r | xlat}}</span>',
                '<b class="caret"></b>',
                '</a>',
                '<ul class="dropdown-menu">',
                '</li>',
                '<li ng-show="comFormUser" class="contactus">',
                '<a href="https://thumbprint.com/Thompson-Thrift/CommunityUpdate/" target="_blank">',
                '{{\'Community Update Form\' | r | xlat}}',
                '</a>',
                '</li>',
                '<li ng-show="user.Permissions.contains(\'ViewSelfAdmin\')" class="admin">',
                '<a href="admin">',
                '{{\'User Information\' | r | xlat}}',
                '</a>',
                '</li>',
                '<li ng-show="user.Type == \'Customer\' && (user.Permissions.contains(\'CreateShipToAddress\') || user.Permissions.contains(\'CreateBillToAddress\'))" class="addresses">',
                '<a href="addresses">',
                '{{\'Addresses\' | r | xlat}}',
                '</a>',
                '</li>',
                '<li ng-show="user.Type == \'Customer\' && user.Permissions.contains(\'ViewMessaging\')" class="messages">',
                '<a href="message">',
                '{{\'Messages\' | r | xlat}}',
                '</a>',
                '</li>',
                '<li ng-show="user.Permissions.contains(\'ViewContactUs\')" class="contactus">',
                '<a href="contactus">',
                '{{\'Contact Us\' | r | xlat}}',
                '</a>',
                '</li>',
                '<li ng-show="user.Type!=\'TempCustomer\' && !user.Permissions.contains(\'PunchoutUser\')" class="logout">',
                '<a href="#" neworder ng-if="user.Permissions.contains(\'MultipleShoppingCart\') && currentOrder" class="neworder" ng-click="newOrderLoadingIndicator = true;startNewOrder()">',
                '{{"Start" | r | xlat}} {{"New" | r | xlat}} {{"Order" | r | xlat}}',
                '</a>',
                '</li>',
                '<li class="divider" ng-show="user.Type!=\'TempCustomer\' || AppConst.debug"></li>',
                '<li ng-show="user.Type!=\'TempCustomer\'" class="logout" ng-hide="PunchoutUser === true">',
                '<a href="#" ng-click="Logout()">',
                '<i class="fa fa-power-off text-danger"></i>',
                '<span>{{\' Log Out\' | r | xlat}}</span>',
                '</a>',
                '</li>',
                '</ul>',
                '</li>',
                '</ul>',
                '</div>',
                '<div class="col-xs-12 col-sm-12 col-md-2 col-lg-4 hidden-xs hidden-sm" style="">',
                '<div class="product-search pull-right col-md-4 col-lg-2" style="margin-top:10px;">',
                // '<productsearchinput></productsearchinput>',
                '<ul class="user-search">',
                //'<li>',
               // '<productsearchinputnav></productsearchinputnav>',
               // '</li>',
                '<li class="user-icon">',
                '<a href="admin">',
                '<i class="fa fa-user"></i>',
                '</a>',
                '</li>',
                '</ul>',
                '</div>',
                '</div>',
            '</div>',
              '<ul class="pull-right hidden-xs hidden-sm">',
              	'<minicart></minicart>',
              '</ul>',
            '</section>'
        ].join('');
    }
}
